apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: learningsteps-api
  namespace: learningsteps
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: "us-east-1"
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:062163939903:secret:rds!db-1bdedf3c-c916-47f0-8461-372c4fee652d-pA0qN4"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "db-password"