apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: learningsteps-api
  namespace: learningsteps
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: "us-east-1"
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:062163939903:secret:rds!db-24d7cdfe-e032-45e1-948a-5d6ee2813416-P99j5u"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "db-password"