apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: learningsteps-api
  namespace: learningsteps
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: "eu-central-1"
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-central-1:518285921450:secret:rds!db-c59338e6-88a3-41cc-a7ed-a94316be2d16-xBrgU2"
        objectType: "secretsmanager"
        jmesPath:
          - path: "password"
            objectAlias: "db-password"