name: Build and push image to ECR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          IMAGE="${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY:${GITHUB_SHA::7}"
          docker build --platform linux/amd64 --provenance=false -f docker/Dockerfile -t "$IMAGE" learningsteps
          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"

      - name: Scan image (Trivy)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: ${{ env.IMAGE }}
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Push image to ECR
        run: docker push "$IMAGE"
